version: '3'
services:
  flask:
    build: server
    command: gunicorn app.main:app --workers 1 --bind 0.0.0.0:5000 --reload
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - PYTHONBUFFER=True
    ports:
    - "5000:5000"
    volumes:
    - ./server:/root